export default [
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
    {
        id: 1,
        job: 'Android Developer',
        name: 'Andrew Garifield',
        mail: 'andrew007@sample.com',
        status: 'Open',
        type: 'Full -time',
        applied_date: 'June 1, 2020',
    },
]
