export default [
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Closed',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Cancelled',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
  {
    job: 'Android Developer',
    // name: 'Direct Security Executive',
    applicants: 3,
    status: 'Open',
    type: 'Full -time',
    date: 'June 1, 2020',
  },
]
